### ISSUE TITLE
Слишком долга обновы идут

### ISSUE THREAD

**Issue by Katze-942** [DarkVessel/mouse-db.json#1]
Жора мыш.

**Comment by KN13KOMETA** [comment]
Жора не  мыш, я протестую.

**Comment by wereami** [comment]
ващет я мышь

**Comment by Katze-942** [comment]
> Жора не мыш, я протестую.

Вы живёте в России где ваше мнение не учитывается! Так шо всё, я мыш я ни слушаю вас

**Comment by Katze-942** [comment]
> ващет я мышь

цыц

**Comment by KN13KOMETA** [comment]
Так <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">мыш</a> это база данных, значит ты не можешь быть мышью.

**Comment by Katze-942** [comment]
заскамил

**Comment by KN13KOMETA** [comment]
Простите случайна.

**Comment by Katze-942** [comment]
прощаю

**Comment by Katze-942** [comment]
Мы нишо не решили поэтому закрываем это
